## **Задание на повторение материала

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [145]:
import numpy as np
import pandas as pd

In [146]:
a = np.arange(12, 24) # тоже что и  a = np.array([i for i in range (12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [147]:
N = a.size  # находим делители размеров нашего массива
 
for d in range (1, N // 2 + 1) :
  if N % d == 0 :
    print (d, ' ', sep = '', end = '')
print (N)

1 2 3 4 6 12


In [148]:
divisor_array = [1, 2, 3, 4, 6, 12]

In [149]:
def get_sorted_pairs(arr): # сортируем их попарно для получения массивов
    result = []
    for i in range (len(arr) // 2):
            result += [(arr[i], arr[len(arr) -1 - i])]
            result += [(arr[len(arr) -1 - i], arr[i])]
    return result

In [150]:
get_sorted_pairs(divisor_array)

[(1, 12), (12, 1), (2, 6), (6, 2), (3, 4), (4, 3)]

In [151]:
len(get_sorted_pairs(divisor_array))

6

In [152]:
x_1 = get_sorted_pairs(divisor_array)[0] # тут у нас косой неоптемезированый кусок, но пока будет так 
x_2 = get_sorted_pairs(divisor_array)[1]
x_3 = get_sorted_pairs(divisor_array)[2]
x_4 = get_sorted_pairs(divisor_array)[3]
x_5 = get_sorted_pairs(divisor_array)[4]
x_6 = get_sorted_pairs(divisor_array)[5]

In [153]:
new_array_1 = a.reshape(x_1[0], x_1[1])
new_array_1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [154]:
new_array_2 = a.reshape(x_2[0], x_2[1])
new_array_2

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [155]:
new_array_3 = a.reshape(x_3[0], x_3[1])
new_array_3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [156]:
new_array_4 = a.reshape(x_4[0], x_4[1])
new_array_4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [157]:
new_array_5 = a.reshape(x_5[0], x_5[1])
new_array_5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [158]:
new_array_6 = a.reshape(x_6[0], x_6[1])
new_array_6

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [159]:
new_array_7 = a.reshape(2, -1)
new_array_7

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [160]:
new_array_8 = a.reshape(3, -1)
new_array_8

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [161]:
new_array_9 = a.reshape(4, -1)
new_array_9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [162]:
new_array_10 = a.reshape(-1, 12)
new_array_10

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [163]:
new_array_11 = a.reshape(-1, 6)
new_array_11

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [164]:
new_array_1 = a.reshape(12, 1)
new_array_1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [212]:
new_array_1.ndim # получаем количество измерений

2

In [203]:
new_array_1.shape 

(12, 1)

Ответ: нет, тут 2 измерения

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [166]:
my_random_array = np.random.randn(3, 4)
my_random_array

array([[ 0.07983181, -0.1595165 ,  0.02222183, -0.42779291],
       [-0.53181741, -0.1174755 ,  0.2220789 , -0.7679765 ],
       [ 0.1424646 , -0.03465218,  1.13433927, -0.10474555]])

In [167]:
my_random_array_size = my_random_array.size
my_random_array_size

12

In [168]:
my_random_array_2 = np.random.sample(my_random_array_size)
my_random_array_2

array([0.68030754, 0.45049925, 0.01326496, 0.94220176, 0.56328822,
       0.3854165 , 0.01596625, 0.23089383, 0.24102547, 0.68326352,
       0.60999666, 0.83319491])

In [169]:
my_random_array.size == my_random_array_2.size

True

#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [207]:
a = np.arange(20, 0, -2) # "Это одноменрный массив 

#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [171]:
b = np.arange(20, 1, -2) 

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [172]:
b.resize(10, 1) # Это двуменрный массив 
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [173]:
a = np.zeros((3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [174]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [175]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [176]:
v.size == 10

True

#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [177]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [178]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [179]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [180]:
B = np.dot(A, At) # перемножаем матрицы 
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [181]:
B.size # Размер матрицы B

16

In [182]:
np.linalg.matrix_rank(B)  # Ранг матрицы B

2

In [183]:
np.linalg.det(B) # Определитель матрицы равен 0, что значит все её строки являются линейно зависимыми. 
                 # Найти одратную матрицу не получится

0.0

Ответ: нет 

#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [184]:
np.random.seed(42)

In [185]:
np.random.randint(-100, 100, 5)

array([  2,  79,  -8, -86,   6])

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [186]:
c = np.random.randint(0, 16, 16)
c

array([ 7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5])

#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [187]:
C = c.reshape(4, 4)
C

array([[ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3],
       [ 7,  7,  2,  5]])

In [188]:
D = np.add(B, C * 10)
D

array([[ 75, 134,  63,  92],
       [104,  70, 146, 222],
       [123, 156, 189, 242],
       [102, 192, 232, 352]])

In [189]:
np.linalg.det(D)

-57500799.99999996

In [190]:
np.linalg.matrix_rank(D)

4

In [191]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.0091797 ,  0.01478936, -0.00057599, -0.01133062],
       [ 0.00726703, -0.00796476, -0.00066816,  0.00358325],
       [-0.0223656 , -0.02002824,  0.03547429, -0.00591157],
       [ 0.0081171 ,  0.01325929, -0.02284942,  0.00806597]])

#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [192]:
D_inv[D_inv < 0] = 0
D_inv

array([[0.0091797 , 0.01478936, 0.        , 0.        ],
       [0.00726703, 0.        , 0.        , 0.00358325],
       [0.        , 0.        , 0.03547429, 0.        ],
       [0.0081171 , 0.01325929, 0.        , 0.00806597]])

In [193]:
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.]])

In [210]:
result = D_inv > 0
result

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [ True,  True, False,  True]])

In [195]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [196]:
C

array([[ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3],
       [ 7,  7,  2,  5]])

In [211]:
E = np.where(result, B, C)    
E

array([[  5,  14,   4,   6],
       [ 14,   2,   6, 122],
       [ 10,   7, 149,   3],
       [ 32, 122,   2, 302]])

#### Альтернативный вариант

In [198]:
D_inv = np.array([[ 0.0091797 ,  0.01478936, -0.00057599, -0.01133062],
                  [ 0.00726703, -0.00796476, -0.00066816,  0.00358325],
                  [-0.0223656 , -0.02002824,  0.03547429, -0.00591157],
                  [ 0.0081171 ,  0.01325929, -0.02284942,  0.00806597]])

In [199]:
D_inv = np.where(D_inv < 0, 0, D_inv)
D_inv

array([[0.0091797 , 0.01478936, 0.        , 0.        ],
       [0.00726703, 0.        , 0.        , 0.00358325],
       [0.        , 0.        , 0.03547429, 0.        ],
       [0.0081171 , 0.01325929, 0.        , 0.00806597]])

In [200]:
D_inv = np.where(D_inv > 0, 1, D_inv) 
D_inv

array([[1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.]])

In [201]:
E = np.where(D_inv, B, C)    # тут у меня возникает вопрос: как этот чертов волшебник понимает, что если 1 то это - True?
E

array([[  5,  14,   4,   6],
       [ 14,   2,   6, 122],
       [ 10,   7, 149,   3],
       [ 32, 122,   2, 302]])