## Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


Импортируем Библиотеку

In [2]:
import numpy as np

берем данные

In [3]:
a = np.array([ 1, 2, 3, 3, 1, 6, 8, 11, 10, 7])
a

array([ 1,  2,  3,  3,  1,  6,  8, 11, 10,  7])

In [4]:
a.shape = (2, 5)
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [5]:
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = np.zeros(2)
mean_a

array([0., 0.])

In [7]:
np.mean(a, axis = 0, out = mean_a)
mean_a

array([2. , 8.4])

## задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [8]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a

array([2. , 8.4])

In [10]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [11]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Извлечем из нашего массива стобцы для последующего их сложения

In [12]:
column0 = a_centered[:, 0]   # извлекаем первый столбец
column0

array([-1.,  0.,  1.,  1., -1.])

In [13]:
column1 = a_centered[:, 1]  # извлекаем второй столбец
column1

array([-2.4, -0.4,  2.6,  1.6, -1.4])

Находим скалярое произведение столбцов

In [14]:
a_centered_sp = np.dot(column0, column1)
a_centered_sp

8.0

Вычислим число наблюдений. Для этого сделаем срез каждой строки.

In [25]:
N = len(a_centered) # получаем количество строк - это количество наблюдений
N

5

In [32]:
ansver_1 = a_centered_sp / (N - 1)
ansver_1

2.0

## задание 4**

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [30]:
m = a.transpose()
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [33]:
covariance_matrix = np.cov(m)
covariance_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [35]:
ansver_2 = covariance_matrix[0, 1]
ansver_2

2.0

In [36]:
ansver_1 == ansver_2

True